### ISSUE TITLE
Mouse Pointer Position Error

### ISSUE THREAD

**Issue by BlackdeerY** [moonlight-stream/nvidia-gamestream-issues#10]
**Describe the bug**
Mouse Pointer Position Error in Specific Programs.

**Steps to reproduce**
No Any Condition. Always Wrong Position in some programs.

**Screenshots**
![IMG_1244](https://user-images.githubusercontent.com/49787913/120878481-c7866600-c5f7-11eb-9f19-795301d59118.gif)

**Affected games**
- Host Program: Adobe Photoshop CS 6 64bit, mspaint.exe

**Moonlight settings (please complete the following information)**
Default

**Device details (please complete the following information)**
- Host OS: Windows 10 20H2
- Geforce Experience version: 3.22.0.32,
- Nvidia GPU driver: 466.27,
- Client: iPadOS 14.6,
- DeviceModel: iPad Air 4th
- Host Program: Adobe Photoshop CS 6 64bit, mspaint.exe

**Server PC details (please complete the following information)**
- Host OS: Windows 10 20H2
- Geforce Experience version: 3.22.0.32,
- Nvidia GPU driver: 466.27,
- Client: iPadOS 14.6,
- DeviceModel: iPad Air 4th
- Host Program: Adobe Photoshop CS 6 64bit, mspaint.exe

**Comment by cgutman** [comment]
This is a known bug in how Nvidia encodes the cursor into the video stream. This is something they will have to fix, so I have transferred this issue to the GameStream bug tracker.

**Comment by branpurn** [comment]
This is observed on high DPI panel on Windows as well-- Macs are virtually all very high DPI panels, so it's probably related in that regard...

**Comment by cgutman** [comment]
NVIDIA is working on a fix - https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/433782/cursor-alignment-issues-in-geforce-experience-sinc/3117651/

**Comment by Openingfuel** [comment]
I played with 'change mouse pointer size' in system settings in windows 10 which solved this problem for me, at least temporarily.

**Comment by NickoLopez** [comment]
Hi any update on this one? It's been month since NVidia said they were working on a fix and the issue is still there.

**Comment by cgutman** [comment]
> Hi any update on this one? It's been month since NVidia said they were working on a fix and the issue is still there.

I wish, but I don't have any insider information about when Nvidia plans to release said fix. They don't communicate with us about things like that.

**Comment by Tsubajashi** [comment]
Did anyone test if the bug got fixed?

**Comment by NickoLopez** [comment]
> Did anyone test if the bug got fixed?

Why, Is there anything to test?

**Comment by hxssgaa** [comment]
Same issue, is there any follow-up for the issue?

**Comment by NickoLopez** [comment]
The issue seems to be gone on my side. Has it been fixed in the latest drivers?

**Comment by rmaenk** [comment]
Hello
This is fixed, according to nvidia forum:
[Cursor alignment issues in Geforce Experience since driver v446](https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/433782/cursor-alignment-issues-in-geforce-experience-sinc/3169983/)
I am using driver 496.76 (November 16, 2021) and issue is gone away.

Regards,
Roman

**Comment by BlackdeerY** [comment]
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/433782/cursor-alignment-issues-in-geforce-experience-sinc/3169734/

In the response from this link,
the mouse position is resolved,
but the mouse scaling still seems to be an issue.

**Comment by StoneWolf** [comment]
I can confirm this is fixed on my computer with the latest drivers. Should this issue be closed?

**Comment by cgutman** [comment]
Yep, closing.

**Comment by markdjohnston** [comment]
Are others not getting this issue anymore? I'm still having the same experience with paint and other programs as the initial report. I'm on a Quadro T1000 which might be the reason.
